- name: Create a DB server using EC2 module
  hosts: localhost
  connection: local
  vars:
    ami: ami-1fbad07c
    sec_group: sg-77602e11
    region: ap-southeast-1
    subnet: subnet-9d05befa
    server: pg_primary
  roles:
    - create-ec2 

- name: Create a Web server using EC2 module
  hosts: localhost
  connection: local
  vars:
    ami: ami-1fbad07c
    sec_group: sg-77602e11
    region: ap-southeast-1
    subnet: subnet-9d05befa
    server: pg_standby0
  roles:
    - create-ec2

# Optional Step which can be skipped if you have added repo manually in AMI itself
- name: Setup EDB Repository
  hosts: pg_servers
  roles:
    - edb_repo_add
    - edb-setup

- name: Install EDB
  hosts: pg_primary
  vars:
    primary_node: true
  roles:
    - create_edb_instance


- name: Install EDB
  hosts: pg_standby*
  vars:
    primary_node: false
  roles:
    - create_edb_instance

