- name: Create EDB Instance
  hosts: pg_primary
  vars:
    SERVICE_NAME: '{{ PGSERVICE  }}'
  roles:
    - create_edb_instance
    - setup_pg_service
  tasks:
    - include_tasks: add-python-dependencies.yml
    - include_tasks: prepare-primary-for-repl.yml 
