    - name: Download the repo file
      get_url:
        dest: /tmp
        url: http://yum.enterprisedb.com/edbrepos/edb-repo-latest.noarch.rpm

    - name: Install the repository rpm
      command: yum install -y /tmp/edb-repo-latest.noarch.rpm
      become: true
    - name: Install Enterprise Linux Repo
      yum:
        name: epel-release
        state: installed
      become: true

    - name: Set username password
      replace:
        path: '{{ edb_repo_file }}'
        regexp: '<username>:<password>'
        replace: "{{ lookup('ini', 'repo.user section=edb_yum_repo file=/home/ansible/credentials.ini') }}:{{ lookup('ini', 'repo.password section=edb_yum_repo file=/home/ansible/credentials.ini') }}"
      become: true

    - name: Enable repos
      ini_file:
        path: '{{ edb_repo_file }}'
        section: '{{ item }}'
        option: enabled
        value: 1
      with_items: '{{ repo_list }}'
      become: true

    - name: Refresh yum meta
      command: yum update meta
      become: true

