---
# tasks file for create-ec2

    - name: Create an EC2 instance
      ec2:
        key_name: MyEC2KeyPair
        instance_type: t2.small
        region: '{{ region }}'
        group_id: '{{ sec_group }}'
        image: '{{ ami }}'
        wait: true
        vpc_subnet_id: '{{ subnet }}'
        volumes:
           - device_name: /dev/sda1
             volume_type: gp2
             volume_size: 20
             delete_on_termination: true
        assign_public_ip: yes
      register: ec2_output


    - name: Add variables for the newly created instance to appropriate file
      blockinfile:
        path: 'host_vars/{{ server }}.yml'
        create: yes
        content: |
              ansible_host: {{ my_server.private_ip }}
              ansible_user: centos
              host_region: {{ my_server.region }}
              instance_type: {{ my_server.instance_type }}
              host_az: {{ my_server.placement }}
              host_os: CentOS
              os_version: 7
      with_items: '{{ ec2_output.instances }}'
      loop_control:
        loop_var: my_server

    - name: Add the new created instance to inventory
      lineinfile:
        path: /etc/ansible/hosts
        line: '{{ server }}'
    - name: Wait for a while before confirming the server is ready
      vars:
        ansible_connection: local
      wait_for: 
        port: 22
        host: '{{ item.private_ip }}'
        delay: 20
      with_items: '{{ ec2_output.instances }}'
